### ISSUE TITLE
new issue on 16.1.2016

### ISSUE THREAD

**Issue by d3tr0l** [jkroepke/2Moons#120]
from few days ago, there must been something changed...when i clone the git repo and use it i cannot even access the installation process of 2moons. got this error:

Warning: Uncaught exception 'ErrorException' with message 'require(includes/config.php): failed to open stream: No such file or directory' in C:\xampp\htdocs\2Moons\includes\classes\Database.class.php:34 Stack trace: #0 C:\xampp\htdocs\2Moons\includes\classes\Database.class.php(34): errorHandler(2, 'require(include...', 'C:\\xampp\\htdocs...', 34, Array) #1 C:\xampp\htdocs\2Moons\includes\classes\Database.class.php(34): Database::__construct() #2 C:\xampp\htdocs\2Moons\includes\classes\Database.class.php(16): Database->__construct() #3 C:\xampp\htdocs\2Moons\includes\classes\cache\builder\VarsBuildCache.class.php(54): Database::get() #4 C:\xampp\htdocs\2Moons\includes\classes\Cache.class.php(103): VarsBuildCache->buildCache() #5 C:\xampp\htdocs\2Moons\includes\classes\Cache.class.php(63): Cache->buildCache('vars') #6 C:\xampp\htdocs\2Moons\includes\vars.php(33): Cache->getData('vars') #7 C:\xampp\htdocs\2Moons\includes\common.php(83): require('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\2Moons\index.php(35): require('C: in C:\xampp\htdocs\2Moons\includes\classes\Database.class.php on line 34

Fatal error: Database::__construct(): Failed opening required 'includes/config.php' (include_path='C:/xampp/htdocs/2Moons/') in C:\xampp\htdocs\2Moons\includes\classes\Database.class.php on line 34

**Comment by d3tr0l** [comment]
got this working...just needed to learn how to update /facepalm...shame on me!
