### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#250]
Update Issue:

After clicking Update:

```
Message: Undefined index: Create Table
File: /includes/classes/SQLDumper.class.php
Line: 102
URL: https://xxxx/install/index.php?mode=doupgrade
PHP-Version: 5.6.21
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
2Moons Version: 1.8.git (FILE)
Debug Backtrace:
#0 /includes/classes/SQLDumper.class.php(102): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 102, Array)
#1 /includes/classes/SQLDumper.class.php(28): SQLDumper->softwareDumpToFile(Array, 'includes/backup...')
#2 /install/index.php(170): SQLDumper->dumpTablesToFile(Array, 'includes/backup...')
#3 {main}
```

**Comment by jkroepke** [comment]
That happens, if 2moons can not find mysqldumer on the system, I did no test this case.

**Comment by jkroepke** [comment]
I added a debug output, maybe you can retry it.?

**Comment by bornhaeusser** [comment]
mmh updated manually in mysql.... so it is already on the newest version. could not roll back.....

**Comment by jkroepke** [comment]
Its okay  got the output in #260
