### ISSUE TITLE
Admin Global message, mode Mail doesn't work

### ISSUE THREAD

**Issue by sunchaser68** [jkroepke/2Moons#266]
While sending a global message from Admin Panel, if I select mode _Mail_ or _Mail and Game_ I have a console error:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
[...] 2Moons/admin.php?page=globalmessage&action=send&ajax=1

```
Response;

```
<body id="overview" class="full">
<table width="960">
	<tr>
		<th>USER ERROR</th>
	</tr>
	<tr>
		<td class="left">
			<b>Message: </b>Invalid address: <br>
			<b>File: </b>/includes/libs/phpmailer/class.phpmailer.php<br>
			<b>Line: </b>1002<br>
			<b>URL: </b>http://www.spacewarlordsgame.com/admin.php?page=globalmessage&action=send&ajax=1<br>
			<b>PHP-Version: </b>5.4.45<br>
			<b>PHP-API: </b>cgi-fcgi<br>
			<b>MySQL-Client-Version: </b>5.5.50<br>
			<b>2Moons Version: </b>1.8.git<br>
			<b>Debug Backtrace:</b><br>#0 /includes/classes/Mail.class.php(79): PHPMailer-&gt;setFrom('', 'Space Warlords')<br>
#1 /includes/classes/Mail.class.php(33): Mail::getMailObject()<br>
#2 /includes/pages/adm/ShowSendMessagesPage.php(76): Mail::multiSend(Array, 'Test Global Mes...')<br>
#3 /admin.php(115): ShowSendMessagesPage()<br>
#4 {main}
		</td>
	</tr>
</table>
</body>
</html>
```

**Comment by OzanKurt** [comment]
It says invalid address... Set a valid one.

**Comment by sunchaser68** [comment]
Whan configured the SMTP address the function works. It doesn't send messages though, but this can depend on my server, i am checking this one.

However, i think if the admin selects SMTP as mail mode, the system should output an error instead of crashing.

Maybe this problem should not be high priority as it pertain to the Admin console.

**Comment by jkroepke** [comment]
@sunchaser68 Currently, the functions depends on the SMTP Sender Address. Maybe I have to rename it.

**Comment by Hilarious001** [comment]
I have no problems if properly configured
