### ISSUE TITLE
[Bug] Server Closed Notice

### ISSUE THREAD

**Issue by Hexeus** [jkroepke/2Moons#293]
Message: Undefined index: PLANETS
File: /includes/pages/game/AbstractGamePage.class.php
Line: 105
URL: https://www.hexeus.com/2Moons/game.php
PHP-Version: 5.6.30
PHP-API: litespeed
MySQL-Client-Version: 5.6.35
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/pages/game/AbstractGamePage.class.php(105): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 105, Array)
#1 /includes/pages/game/AbstractGamePage.class.php(164): AbstractGamePage->getNavigationData()
#2 /includes/pages/game/AbstractGamePage.class.php(234): AbstractGamePage->getPageData()
#3 /includes/pages/game/AbstractGamePage.class.php(215): AbstractGamePage->display('error.default.t...')
#4 /includes/pages/game/ShowErrorPage.class.php(34): AbstractGamePage->printMessage('The game is cur...', false, NULL)
#5 /includes/common.php(168): ShowErrorPage::printError('The game is cur...', false)
#6 /game.php(24): require('FILEPATH ...')
#7 {main}

**Comment by Hilarious001** [comment]
Game link deleted ? still going on with 2moons or ?
