### ISSUE TITLE
[Bug] Deleting a planet

### ISSUE THREAD

**Issue by Hexeus** [jkroepke/2Moons#294]
Message: Can not found planet #12!
File: /includes/classes/PlayerUtil.class.php
Line: 532
URL: https://www.2moons.hexeus.com/admin.php?page=search&delete=planet&planet=12
PHP-Version: 5.6.30
PHP-API: litespeed
MySQL-Client-Version: 5.6.35
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/pages/adm/ShowSearchPage.php(28): PlayerUtil::deletePlanet(12)
#1 /admin.php(135): ShowSearchPage()
#2 {main}

I try to delete a planet but I get this message and the planet is still there.

**Comment by Hilarious001** [comment]
you probably try to delete home planet of player
