### ISSUE TITLE
[Bug] Fleet? Error

### ISSUE THREAD

**Issue by Hexeus** [jkroepke/2Moons#300]
NOTICE
Message: Undefined index: universe
File: /includes/classes/class.PlanetRessUpdate.php
Line: 96
URL: https://2moons.hexeus.com/game.php
PHP-Version: 5.6.30
PHP-API: litespeed
MySQL-Client-Version: 5.6.35
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/class.PlanetRessUpdate.php(96): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 96, Array)
#1 /includes/classes/missions/MissionCaseDestruction.class.php(84): ResourceUpdate->CalcResource(Array, false, true, '1496354016')
#2 /includes/classes/class.FlyingFleetHandler.php(80): MissionCaseDestruction->TargetEvent()
#3 /includes/FleetHandler.php(31): FlyingFleetHandler->run()
#4 /includes/common.php(140): require('FILEPATH ...')
#5 /game.php(24): require('FILEPATH ...')
#6 {main}

**Comment by Hilarious001** [comment]
Hello,

You have to verify if a moon still exist on that spot, before starting the mission

**Comment by jkroepke** [comment]
The problem is if 2 players start a destruction mission and the first missions destory the moon, the 2nd mission will hit this error above.

**Comment by Hilarious001** [comment]
Yes i know, thats why i told him to check if planet still exist., i have the fix since long time, will pr it after rl work

**Comment by xpowert** [comment]
Can you share the fix please ?
