### ISSUE TITLE
admin panel error (probably due php version)

### ISSUE THREAD

**Issue by uranio-235** [jkroepke/2Moons#316]
what PHP's version shall I use? it works fine in debian 9?

```
[lazaro@artema ~]$ php -v
PHP 7.1.8 (cli) (built: Aug  1 2017 20:49:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```
Message: Declaration of Database_BC::query($resource) should be compatible with mysqli::query($query, $resultmode = NULL)
File: /includes/classes/Database_BC.class.php
Line: 269
URL: http://127.0.0.1/~lazaro/admin.php
PHP-Version: 7.1.8
PHP-API: apache2handler
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/common.php(97): errorHandler(2, 'Declaration of ...', 'FILEPATH ...', 269, Array)
#1 /includes/common.php(97): require()
#2 /admin.php(23): require('FILEPATH ...')
#3 {main} 
```

**Comment by lilmnm-kamikaze-** [comment]
https://github.com/jkroepke/2Moons/blob/master/install/index.php#L281

As long as you have version 5.3.0 or higher it should work.  7.1.8 im not sure about. you will have to look at the PHP changlogs to see what has been removed or changed.

**Comment by jkroepke** [comment]
Please test the changes in #317
