### ISSUE TITLE
imposible playing while attack incoming

### ISSUE THREAD

**Issue by uranio-235** [jkroepke/2Moons#319]
When somebody atack, you can only sit down and wait, because game render this error

```
Message: sprintf(): Too few arguments
File: /includes/classes/class.FlyingFleetsTable.php
Line: 220
URL: http://xnova.hcg.sld.cu/game.php
PHP-Version: 7.0.19-1
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 [internal function]: errorHandler(2, 'sprintf(): Too ...', '/i...', 220, Array)
#1 /includes/classes/class.FlyingFleetsTable.php(220): sprintf('Una %s hostil d...', '<a href="#" dat...', 'lazaro <a href=...', 'Planeta', 'Laconia', '<a href="game.p...', 'Planeta', 'Seres Hive', '<a href="game.p...', 'Atacar')
#2 /includes/classes/class.FlyingFleetsTable.php(141): FlyingFleetsTable->getEventData(Array, 0)
#3 /includes/classes/class.FlyingFleetsTable.php(94): FlyingFleetsTable->BuildFleetEventTable(Array, 0)
#4 /includes/pages/game/ShowOverviewPage.class.php(74): FlyingFleetsTable->renderTable()
#5 /includes/pages/game/ShowOverviewPage.class.php(280): ShowOverviewPage->GetFleets()
#6 /game.php(57): ShowOverviewPage->show()
#7 {main} 
```

**Comment by jkroepke** [comment]
Do you modify any language file?

**Comment by uranio-235** [comment]
nop! modifing not, but using spanish, I solved changin line 220 by a string concatenating instead os sprintf, therefore, message are almost imposibe to understand

**Comment by jkroepke** [comment]
does it happend with other langauges, too?

**Comment by ApoRes1337** [comment]
In the German and English version one does not have this error.
